apiVersion: v1
kind: ConfigMap
metadata:
  name: producthub-config
  namespace: producthub
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  MONGO_HOST: "producthub-mongo"
  MONGO_PORT: "27017"
  MONGO_DB_NAME: "producthub"
  MONGO_USER: ""
  MONGO_PASSWORD: ""
  JWT_LIFE_DAYS: "7"
---
apiVersion: v1
kind: Secret
metadata:
  name: producthub-secrets
  namespace: producthub
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-8lp#nbik+r+fn(+qtwd$7@4^oda7f@3+3o*!tdw5fn_uq03n*="
  JWT_SECRET: "super-secret"
